<?php 

/**
 * Implementation of hook_menu()
 */

function ceenclientdemo_menu() {
  $items = array();
  
  $items['ceen'] = array(
    'title' => 'CEEN Resource Search',
    'page callback' => 'ceenclientdemo_example_page_index',
    'access arguments' => array('access content'),
  );
  
  $items['ceen/add'] = array(
    'title' => 'Add a CEEN resource',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ceenclientdemo_add_resource'),
    'access arguments' => array('access administration pages'),
  );
  
  $items['ceen/%'] = array(
    'title' => 'CEEN index',
    'page callback' => 'ceenclientdemo_example_page_individual',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  
  $items['ceen/%/view'] = array(
    'title' => 'CEEN index',
    'page callback' => 'ceenclientdemo_example_page_individual',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['ceen/%/edit'] = array(
    'title' => 'Edit CEEN resource',
    'page callback' => 'ceenclientdemo_edit_resource',
    'page arguments' => array(1),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

function ceenclientdemo_example_page_index() {
  $ceenclient_api_url = variable_get('ceenclient_service_url', '');
  
  $searchOptions = array();
  
  if (isset($_GET)) {
    foreach($_GET as $key => $value) {
      if ($key == 'title') {
        $searchOptions['title'] = $value;
      }
    }
  }
  
  $data = ceenclient_resource_call($ceenclient_api_url . '/resource', 'resource_resource.index', $searchOptions);
  
  $return = '<p>' . l('Data Source', $ceenclient_api_url . '/resource?' . drupal_query_string_encode($searchOptions)) . '</p>';
  
  $return .= drupal_get_form('ceenclientdemo_search_resources');
  
  $return .= kpr($data, true);

  foreach($data['resources'] as $item) {
    $return .= "<p>" . l($item['title'], 'ceen/' . $item['uuid']) . "</p>";
  }
  
  return $return;
}

function ceenclientdemo_example_page_individual($uuid) {
  $ceenclient_api_url = variable_get('ceenclient_service_url', '');
  $data = ceenclient_resource_call($ceenclient_api_url . '/resource/' . $uuid, 'resource_resource.retrieve');
  
  return l('Data Source', $ceenclient_api_url . '/resource/' . $uuid) . kpr($data, true);
}

function ceenclientdemo_search_resources() {
  $form = array(
    '#method' => 'get',
    '#submit' => 'ceenclientdemo_search_resources_submit',
  );
  
  $form['title'] = array(
    '#title' => 'Resource Title',
    '#type' => 'textfield',
    '#default_value' => urldecode($_GET['title']),
  );
  
  $form['#token'] = FALSE;
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  
  return $form;  
}

function ceenclientdemo_add_resource() {
  $form = array();
  
  $form['title'] = array(
    '#title' => t('Resource Title'),
    '#type' => 'textfield',
    '#default_value' => '',
  );
  
  $form['from_time'] = array(
    '#title' => t('Time: From'),
    '#type' => 'textfield',
    '#description' => 'Format: 07/14/2010 - 8:13am',
  );
  
  $form['to_time'] = array(
    '#title' => t('Time: To'),
    '#type' => 'textfield',
    '#description' => 'Format: 07/14/2010 - 8:13am',
  );
  
  $form['description'] = array(
    '#title' => 'Description',
    '#type' => 'textarea',
  );
  
  $form['fair_usage'] = array(
    '#title' => t('Fair Usage'),
    '#type' => 'checkbox',
    '#options' => array(
      1 => t("Grant permission"),
    ),
    '#default_value' => 1,
    '#description' => 'Do you want to grant ConEd permission to publish your resource?',
  );
    
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save Resource',
  );
  
  return $form;
}

function ceenclientdemo_edit_resource($uuid) {
  $ceenclient_api_url = variable_get('ceenclient_service_url', '');
  $data = ceenclient_resource_call($ceenclient_api_url . '/resource/' . $uuid, 'resource_resource.retrieve');
  //kpr($data);

  return drupal_get_form('ceenclientdemo_edit_resource_form', $data);
}

function ceenclientdemo_edit_resource_form(&$form_state, $resource = array()) {
  $form = array();
  
  $form['title'] = array(
    '#title' => t('Resource Title'),
    '#type' => 'textfield',
    '#default_value' => $resource['title'],
  );
  
  $form['ceen_uuid'] = array(
    '#type' => 'value',
    '#value' => $resource['uuid'],
  );
    
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Update Resource',
  );
  
  $form['delete'] = array(
    '#type' => 'submit',
    '#value' => 'Delete Resource',
  );
  
  return $form;
}

function ceenclientdemo_add_resource_submit($form, &$form_state) {
  $data = array(
    'title' => $form_state['values']['title'],
    'description' => $form_state['values']['description'],
    'time' => array(
      'start' => $form_state['values']['from_time'],
      'end' => $form_state['values']['to_time'],
    ),
    'user' => 'eee53b40-847c-11df-aea7-4c3d4dcb12f9', // TMP hardcoded
    'fair_usage' => $form_state['values']['fair_usage'],
  );
  
  $return = ceenclient_resource_call(variable_get('ceenclient_service_url', '') . '/resource', 'resource_resource.create', $data, 'POST');
      
  drupal_set_message('Resource Added', 'status');
  drupal_goto('ceen');
}

function ceenclientdemo_edit_resource_form_submit($form, &$form_state) {
  $message = '';
  if ($form_state['clicked_button']['#value'] == 'Delete Resource') {
    $data = array();
    $return = ceenclient_resource_call(variable_get('ceenclient_service_url', '') . '/resource/' . $form_state['values']['ceen_uuid'], 'resource_resource.delete', $data, 'DELETE');
    $message = 'Resource Deleted';
  } else {
    $data = array(
      'title' => $form_state['values']['title'],
      'user' => 'eee53b40-847c-11df-aea7-4c3d4dcb12f9', // TMP hardcoded
    );
    
    $return = ceenclient_resource_call(variable_get('ceenclient_service_url', '') . '/resource/' . $form_state['values']['ceen_uuid'], 'resource_resource.update', $data, 'PUT');
    $message = 'Resource Updated';
  }
    
  drupal_set_message($message, 'status');
  drupal_goto('ceen');
}