<?php

/**
 * Implements hook_menu()
 */

function ceenclientdevel_menu() {
  $items = array();
  
  $items['ceern_sanity_check'] = array(
    'title' => 'CEERN Sanity Check',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'ceenclientdevel_sanity_check',
  );
      
  return $items;
}

function ceenclientdevel_sanity_check() {
  $data = ceenclient_resource_call(variable_get('ceenclient_service_url', '') . '/resource');
  kpr($data);
  
  foreach ($data['resources'] as $resource) {
    kpr(ceenclient_resource_call(variable_get('ceenclient_service_url', '') . '/resource/' . $resource['uuid']));
  }
}

function ceenclientdevel_ceen_resource_call($uri, $params, $method, $return_data, $datasource) {
  watchdog('CEERN Debugging', 'API Call ' . $method . ' ' . $uri . " <pre>" . print_r($params, true) . "</pre>", array(), WATCHDOG_DEBUG);
  watchdog('CEERN Debugging', 'API Return <pre>' . print_r($return_data, true) . '</pre>', array(), WATCHDOG_DEBUG);
}